---
name: Develhope Maven exercise assessment
on:
  push:

jobs:
  compile:
    name: Maven compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build
        run: |
          chmod 700 mvnw
          ./mvnw compile
        
  lint:
    needs: compile
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        tool_name: 'testtool'
          
